
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (1,'Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (20,'Wing in ground (WIG), all ships of this type');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (21,'Wing in ground (WIG), Hazardous category A');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (22,'Wing in ground (WIG), Hazardous category B');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (23,'Wing in ground (WIG), Hazardous category C');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (24,'Wing in ground (WIG), Hazardous category D');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (25,'Wing in ground (WIG), Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (26,'Wing in ground (WIG), Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (27,'Wing in ground (WIG), Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (28,'Wing in ground (WIG), Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (29,'Wing in ground (WIG), Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (30,'Fishing');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (31,'Towing');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (32,'Towing: length exceeds 200m or breadth exceeds 25m');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (33,'Dredging or underwater ops');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (34,'Diving ops');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (35,'Military ops');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (36,'Sailing');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (37,'Pleasure Craft');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (38,'Reserved');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (39,'Reserved');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (40,'High speed craft (HSC), all ships of this type');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (41,'High speed craft (HSC), Hazardous category A');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (42,'High speed craft (HSC), Hazardous category B');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (43,'High speed craft (HSC), Hazardous category C');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (44,'High speed craft (HSC), Hazardous category D');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (45,'High speed craft (HSC), Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (46,'High speed craft (HSC), Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (47,'High speed craft (HSC), Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (48,'High speed craft (HSC), Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (49,'High speed craft (HSC), No additional information');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (50,'Pilot Vessel');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (51,'Search and Rescue vessel');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (52,'Tug');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (53,'Port Tender');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (54,'Anti-pollution equipment');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (55,'Law Enforcement');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (56,'Spare - Local Vessel');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (57,'Spare - Local Vessel');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (58,'Medical Transport');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (59,'Noncombatant ship according to RR Resolution No. 18');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (60,'Passenger, all ships of this type');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (61,'Passenger, Hazardous category A');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (62,'Passenger, Hazardous category B');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (63,'Passenger, Hazardous category C');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (64,'Passenger, Hazardous category D');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (65,'Passenger, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (66,'Passenger, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (67,'Passenger, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (68,'Passenger, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (69,'Passenger, No additional information');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (70,'Cargo, all ships of this type');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (71,'Cargo, Hazardous category A');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (72,'Cargo, Hazardous category B');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (73,'Cargo, Hazardous category C');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (74,'Cargo, Hazardous category D');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (75,'Cargo, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (76,'Cargo, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (77,'Cargo, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (78,'Cargo, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (79,'Cargo, No additional information');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (80,'Tanker, all ships of this type');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (81,'Tanker, Hazardous category A');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (82,'Tanker, Hazardous category B');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (83,'Tanker, Hazardous category C');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (84,'Tanker, Hazardous category D');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (85,'Tanker, Reserved for future use)');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (86,'Tanker, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (87,'Tanker, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (88,'Tanker, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (89,'Tanker, No additional information');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (90,'Other Type, all ships of this type');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (91,'Other Type, Hazardous category A');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (92,'Other Type, Hazardous category B');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (93,'Other Type, Hazardous category C');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (94,'Other Type, Hazardous category D');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (95,'Other Type, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (96,'Other Type, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (97,'Other Type, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (98,'Other Type, Reserved for future use');
INSERT INTO TYPE_SHIP (ID,DESCRIPTION) VALUES (99,'Other Type, no additional information');

INSERT INTO SHIPS (ID,ACTIVE,COUNTRY,DESTINATION,DISTANCE,SPEED,IMG,IN_AREA,MMSI) VALUES
(1,'false','Norge','TRONDHEIM',0,0,'https://localhost:443/ship/deflaut_ship.png','false',257599700);
INSERT INTO SHIPS (ID,ACTIVE,COUNTRY,DESTINATION,DISTANCE,SPEED,IMG,IN_AREA,MMSI) VALUES
(2,'true','Norge','TRONDHEIM',0.24891699797412814,0,'https://localhost:443/ship/deflaut_ship.png','true',257304900);
INSERT INTO SHIPS (ID,ACTIVE,COUNTRY,DESTINATION,DISTANCE,SPEED,IMG,IN_AREA,MMSI) VALUES
(3,false,'Norge','TRONDHEIM',0.6,0,'https://localhost:443/ship/deflaut_ship.png','true',257304800);


INSERT INTO SHIP_POINT (ID,CREATE_DATE_TIME,X_COORDINATE,Y_COORDINATE) VALUES
(83,'2023-09-28 12:35:01',63.437818,10.396908),
(119,'2023-09-28 12:36:01',63.437808,10.39693),
(153,'2023-09-28 12:36:01',63.437808,10.39693),
(187,'2023-09-28 12:36:01',63.437808,10.39693),
(224,'2023-09-28 12:37:01',63.437825,10.396928),
(258,'2023-09-28 12:37:01',63.437825,10.396928),
(292,'2023-09-28 12:37:01',63.437825,10.396928),
(328,'2023-09-28 12:38:00',	63.43783,10.396932),
(362,'2023-09-28 12:38:00',	63.43783,10.396932);


INSERT INTO SHIP_POINT (ID,CREATE_DATE_TIME,X_COORDINATE,Y_COORDINATE) VALUES
(71,'2023-09-28 12:29:09',63.439142,10.501895),
(105,'2023-09-28 12:29:09',63.439142,10.501895),
(139,'2023-09-28 12:29:09',63.439142,10.501895),
(173,'2023-09-28 12:29:09',63.439142,10.501895),
(207,'2023-09-28 12:29:09',63.439142,10.501895),
(241,'2023-09-28 12:29:09',63.439142,10.501895),
(275,'2023-09-28 12:29:09',63.439142,10.501895),
(308,'2023-09-28 12:29:09',63.439142,10.501895);

INSERT INTO SHIPS_TRACK (SHIP_ID,TRACK_ID) VALUES (1,71),(1,105),(1,139),(1,173),(1,207),(1,241),(1,275),(1,308);
INSERT INTO SHIPS_TRACK (SHIP_ID,TRACK_ID) VALUES (2,83),(2,119),(2,153),(2,187),(2,224),(2,258),(2,292),(2,328);

INSERT INTO USERS (ID,USERNAME,PASSWORD,ENABLED,EMAIL,ROLE) VALUES
 (1,'admin','admin',TRUE,'dragon.marcel@o2.pl','ADMIN'),
 (2,'user','user',TRUE,'user@o2.pl','USER');

INSERT INTO SHIPS_TRACKED_BY VALUES(1,1)